# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "moqueue"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel DeLeo"]
  s.date = "2012-05-09"
  s.description = "Mocktacular Companion to AMQP Library. Happy TATFTing!"
  s.email = ["dan@kallistec.com"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CONTRIBUTORS.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "lib/moqueue.rb",
    "lib/moqueue/fibers18.rb",
    "lib/moqueue/matchers.rb",
    "lib/moqueue/mock_broker.rb",
    "lib/moqueue/mock_exchange.rb",
    "lib/moqueue/mock_headers.rb",
    "lib/moqueue/mock_queue.rb",
    "lib/moqueue/mock_session.rb",
    "lib/moqueue/object_methods.rb",
    "lib/moqueue/overloads.rb",
    "moqueue.gemspec",
    "spec/examples/ack_spec.rb",
    "spec/examples/basic_usage_spec.rb",
    "spec/examples/example_helper.rb",
    "spec/examples/logger_spec.rb",
    "spec/examples/ping_pong_spec.rb",
    "spec/examples/stocks_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/unit/matchers_spec.rb",
    "spec/unit/mock_broker_spec.rb",
    "spec/unit/mock_exchange_spec.rb",
    "spec/unit/mock_headers_spec.rb",
    "spec/unit/mock_queue_spec.rb",
    "spec/unit/mock_session_spec.rb",
    "spec/unit/moqueue_spec.rb",
    "spec/unit/object_methods_spec.rb",
    "spec/unit/overloads_spec.rb"
  ]
  s.homepage = "https://github.com/customink/moqueue"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Mocktacular Companion to AMQP Library. Happy TATFTing!"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<amqp>, [">= 0.9.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 1.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<amqp>, [">= 0.9.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 1.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<amqp>, [">= 0.9.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 1.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

